plugin:
  id: helloworldplugin
  displayname: Hello World Plugin
  description: This is a sample hello world plugin.
  version: 0.0.5
  icon:
    name: fa-solid fa-globe
    color: blue
  git_repo:
    url: https://github.com/Torrent007/helloworld-plugin.git
    branch: master
  documentation: https://github.com/Torrent007/helloworld-plugin/blob/master/README.md
  author: Fabien EGRET
  contributors: []
  roles:
    - name: Full Control
      description: Complete control over the plugin
      ldap_group: LDAP_FAKE_GROUP_FULLCONTROL
    - name: Users
      description: Minimal access to the plugin.
      ldap_group: LDAP_FAKE_GROUP_USERS
    - name: Read Only
      description: Read only access to the plugin.
      ldap_group: LDAP_FAKE_GROUP_READONLY
    - name: Partial Control
      description: Partial control over the plugin.
      ldap_group: LDAP_FAKE_GROUP_PARTIALCONTROL

backend:
  root_url: hello-world

frontend: 
  root_url: hello-world
  title: Hello World
  icon: ki-filled ki-like
  sidebar:
    - title: Single item
      link: /single-item
      icon: 
    - title: Multiple items
      icon: 
      items:
        - title: Item 1
          link: /item1
        - title: Item 2
          link: /item2
